//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamzawey
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HamzaweyEntities1 : DbContext
    {
        public HamzaweyEntities1()
            : base("name=HamzaweyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<newproduct> newproducts { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<clientstbl> clientstbls { get; set; }
        public virtual DbSet<supplierstbl> supplierstbls { get; set; }
    }
}
